# Generated by Django 2.2 on 2021-05-15 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_post_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lista', models.CharField(max_length=100)),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='website.Post')),
            ],
        ),
    ]
